const axios = require('axios');
async function getData(id) {
    const url1 = 'http://localhost:4200/api/coins/'+id;
    const url2 = 'http://localhost:4200/api/vote/state/'+id;
    const url3 = 'http://localhost:4200/api/vote/total/'+id;
    const a = await axios.get(url1);
    const item = a.data;
    const data = {
        _id :  item._id,
        about: item.about,
            name :  item.basedata.name,
            price: {
              BTC : item.marketdata.price.BTC.toFixed(8),
              USD : item.marketdata.price.USD.toFixed(2),
              AUD : item.marketdata.price.AUD.toFixed(2),
              BGN : item.marketdata.price.BGN.toFixed(2),
              BRL : item.marketdata.price.BRL.toFixed(2),
              CAD : item.marketdata.price.CAD.toFixed(2),
              CHF : item.marketdata.price.CHF.toFixed(2),
              CNY : item.marketdata.price.CNY.toFixed(2),
              CZK : item.marketdata.price.CZK.toFixed(2),
              EUR : item.marketdata.price.EUR.toFixed(2),
              JPY : item.marketdata.price.JPY.toFixed(2),
              KRW : item.marketdata.price.KRW.toFixed(2),
              VND : item.marketdata.price.VND.toFixed(2),
              RUB : item.marketdata.price.RUB.toFixed(2),
            },
            change : item.marketdata.change,
            volume : { 
              BTC : item.marketdata.volume.BTC.toFixed(2),
              USD : item.marketdata.volume.USD.toFixed(2),
              AUD : item.marketdata.volume.AUD.toFixed(2),
              BGN : item.marketdata.volume.BGN.toFixed(2),
              BRL : item.marketdata.volume.BRL.toFixed(2),
              CAD : item.marketdata.volume.CAD.toFixed(2),
              CHF : item.marketdata.volume.CHF.toFixed(2),
              CNY : item.marketdata.volume.CNY.toFixed(2),
              CZK : item.marketdata.volume.CZK.toFixed(2),
              EUR : item.marketdata.volume.EUR.toFixed(2),
              JPY : item.marketdata.volume.JPY.toFixed(2),
              KRW : item.marketdata.volume.KRW.toFixed(2),
              VND : item.marketdata.volume.VND.toFixed(2),
              RUB : item.marketdata.volume.RUB.toFixed(2),
            },
            marketcap : {
              BTC : item.marketdata.marketcap.BTC.toFixed(2),
              USD : item.marketdata.marketcap.USD.toFixed(2),
              AUD : item.marketdata.marketcap.AUD.toFixed(2),
              BGN : item.marketdata.marketcap.BGN.toFixed(2),
              BRL : item.marketdata.marketcap.BRL.toFixed(2),
              CAD : item.marketdata.marketcap.CAD.toFixed(2),
              CHF : item.marketdata.marketcap.CHF.toFixed(2),
              CNY : item.marketdata.marketcap.CNY.toFixed(2),
              CZK : item.marketdata.marketcap.CZK.toFixed(2),
              EUR : item.marketdata.marketcap.EUR.toFixed(2),
              JPY : item.marketdata.marketcap.JPY.toFixed(2),
              KRW : item.marketdata.marketcap.KRW.toFixed(2),
              VND : item.marketdata.marketcap.VND.toFixed(2),
              RUB : item.marketdata.marketcap.RUB.toFixed(2),
            },
            dailyincome: {
                coin: item.incomedata.dailyincome.coin.toFixed(4),
                BTC: item.incomedata.dailyincome.BTC.toFixed(8),
                USD: item.incomedata.dailyincome.USD.toFixed(2),
                AUD: item.incomedata.dailyincome.AUD.toFixed(2),
                BGN: item.incomedata.dailyincome.BGN.toFixed(2),
                BRL: item.incomedata.dailyincome.BRL.toFixed(2),
                CAD: item.incomedata.dailyincome.CAD.toFixed(2),
                CHF: item.incomedata.dailyincome.CHF.toFixed(2),
                CNY: item.incomedata.dailyincome.CNY.toFixed(2),
                CZK: item.incomedata.dailyincome.CZK.toFixed(2),
                EUR: item.incomedata.dailyincome.EUR.toFixed(2),
                JPY: item.incomedata.dailyincome.JPY.toFixed(2),
                KRW: item.incomedata.dailyincome.KRW.toFixed(2),
                VND: item.incomedata.dailyincome.VND.toFixed(2),
                RUB: item.incomedata.dailyincome.RUB.toFixed(2),
              },
              weeklyincome: {
                coin: item.incomedata.weeklyincome.coin.toFixed(4),
                BTC: item.incomedata.weeklyincome.BTC.toFixed(8),
                USD: item.incomedata.weeklyincome.USD.toFixed(2),
                AUD: item.incomedata.weeklyincome.AUD.toFixed(2),
                BGN: item.incomedata.weeklyincome.BGN.toFixed(2),
                BRL: item.incomedata.weeklyincome.BRL.toFixed(2),
                CAD: item.incomedata.weeklyincome.CAD.toFixed(2),
                CHF: item.incomedata.weeklyincome.CHF.toFixed(2),
                CNY: item.incomedata.weeklyincome.CNY.toFixed(2),
                CZK: item.incomedata.weeklyincome.CZK.toFixed(2),
                EUR: item.incomedata.weeklyincome.EUR.toFixed(2),
                JPY: item.incomedata.weeklyincome.JPY.toFixed(2),
                KRW: item.incomedata.weeklyincome.KRW.toFixed(2),
                VND: item.incomedata.weeklyincome.VND.toFixed(2),
                RUB: item.incomedata.weeklyincome.RUB.toFixed(2),
              },
              monthlyincome: {
                coin: item.incomedata.monthlyincome.coin.toFixed(4),
                BTC: item.incomedata.monthlyincome.BTC.toFixed(8),
                USD: item.incomedata.monthlyincome.USD.toFixed(2),
                AUD: item.incomedata.monthlyincome.AUD.toFixed(2),
                BGN: item.incomedata.monthlyincome.BGN.toFixed(2),
                BRL: item.incomedata.monthlyincome.BRL.toFixed(2),
                CAD: item.incomedata.monthlyincome.CAD.toFixed(2),
                CHF: item.incomedata.monthlyincome.CHF.toFixed(2),
                CNY: item.incomedata.monthlyincome.CNY.toFixed(2),
                CZK: item.incomedata.monthlyincome.CZK.toFixed(2),
                EUR: item.incomedata.monthlyincome.EUR.toFixed(2),
                JPY: item.incomedata.monthlyincome.JPY.toFixed(2),
                KRW: item.incomedata.monthlyincome.KRW.toFixed(2),
                VND: item.incomedata.monthlyincome.VND.toFixed(2),
                RUB: item.incomedata.monthlyincome.RUB.toFixed(2),
              },
              yearlyincome: {
                coin: item.incomedata.yearlyincome.coin.toFixed(4),
                BTC: item.incomedata.yearlyincome.BTC.toFixed(8),
                USD: item.incomedata.yearlyincome.USD.toFixed(2),
                AUD: item.incomedata.yearlyincome.AUD.toFixed(2),
                BGN: item.incomedata.yearlyincome.BGN.toFixed(2),
                BRL: item.incomedata.yearlyincome.BRL.toFixed(2),
                CAD: item.incomedata.yearlyincome.CAD.toFixed(2),
                CHF: item.incomedata.yearlyincome.CHF.toFixed(2),
                CNY: item.incomedata.yearlyincome.CNY.toFixed(2),
                CZK: item.incomedata.yearlyincome.CZK.toFixed(2),
                EUR: item.incomedata.yearlyincome.EUR.toFixed(2),
                JPY: item.incomedata.yearlyincome.JPY.toFixed(2),
                KRW: item.incomedata.yearlyincome.KRW.toFixed(2),
                VND: item.incomedata.yearlyincome.VND.toFixed(2),
                RUB: item.incomedata.yearlyincome.RUB.toFixed(2),
              },
            roi : item.incomedata.roi,
            mncount : item.explorerdata.mncount,
            share: item.share
    }
return data;
}
export default getData;